/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mumumusuc_joycon_Joycon */

#ifndef _Included_com_mumumusuc_joycon_Joycon
#define _Included_com_mumumusuc_joycon_Joycon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeInit
 * Signature: (Ljava/nio/ByteBuffer;?;?)I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_joycon_Joycon_nativeInit
        (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeFree
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_joycon_Joycon_nativeFree
        (JNIEnv *, jobject);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeReplayOutputReport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_joycon_Joycon_nativeReplayOutputReport
        (JNIEnv *, jobject);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeMakeupInputReport
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mumumusuc_joycon_Joycon_nativeMakeupInputReport
        (JNIEnv *, jobject);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeUpdateButtons
 * Signature: ([Z)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_joycon_Joycon_nativeUpdateButtons
        (JNIEnv *, jobject, jbooleanArray);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeUpdateSticks
 * Signature: ([C)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_joycon_Joycon_nativeUpdateSticks
        (JNIEnv *, jobject, jcharArray);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeUpdateIMU
 * Signature: ([S[S)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_joycon_Joycon_nativeUpdateIMU
        (JNIEnv *, jobject, jshortArray, jshortArray);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeUpdateNFC
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_joycon_Joycon_nativeUpdateNFC
        (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mumumusuc_joycon_Joycon
 * Method:    nativeUpdateIR
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_mumumusuc_joycon_Joycon_nativeUpdateIR
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
